### ISSUE TITLE
The given terraform elementsw example erroring out.

### ISSUE THREAD

**Issue by jacobjohnanda** [NetApp/terraform-provider-netapp-elementsw#1]
**Description:-**
The given terraform elementsw example erroring out with the following error:-
====================================================
elementsw_account.test-account: Creating...

Error: invalid character '<' looking for beginning of value

  on resources.tf line 2, in resource "elementsw_account" "test-account":
   2: resource "elementsw_account" "test-account" {
====================================================
All the required packages have been installed

**Terraform Version:-**
[root@rhel6 elementsw]# terraform version
Terraform v0.12.24
+ provider.netapp-elementsw (unversioned)

**Go version:-**
[root@rhel6 elementsw]# go version
go version go1.14.1 linux/amd64

**Comment by lonico** [comment]
fixed by #2

**Comment by lonico** [comment]
fixed with eae2a937e65e892f7392962f44c5a9e9cb08de01
