### ISSUE TITLE
Tag, build, release?

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/terraform-provider-netapp-elementsw#8]
It was hard to figure out adjustments required Terraform v0.13.... Can we make this easier, say by creating tagged releases and binary builds on Github or even publish to the official Hashicorp registry?

**Comment by lonico** [comment]
We'll look into the registry.   We did it for 
https://registry.terraform.io/search/providers?q=netapp

**Comment by scaleoutsean** [comment]
That would be great! 

I'm going to work on some examples that can be used with VMware and being able to install automatically like most other providers would mean a lot for new users.

**Comment by scaleoutsean** [comment]
Excellent news, thank you!

https://registry.terraform.io/providers/NetApp/netapp-elementsw/latest
